logging:
  level:
    root: INFO
    ru.seeker.service.ExcelService: INFO
    ru.seeker.service.ParseService: INFO
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN

server:
  port: 8080 # 8443 for TLS
  shutdown: graceful
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/seeker}
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
#  ssl:
#    enabled: true
#    protocol: TLS
#    enabled-protocols: TLSv1.3
#    ciphers: TLS_AES_128_GCM_SHA256
#    client-auth: none
#
#    key-store: seekerServerKey.jks
#    key-store-password: keyPassWpr24
#    key-store-type: PKCS12
##    key-alias: seekerServerKey
#    key-password: keyPassWpr24
#
#    trust-store: servertruststore.jks
#    trust-store-password: keyPassWpr24
#    trust-store-type: PKCS12

spring:
  main:
    allow-circular-references: false
    lazy-initialization: true # для dev - false, для prod - true.
    allow-bean-definition-overriding: false

  application:
    name: ExcelSeekerService
    version: 1.0.5

  profiles:
    active: dev
    default: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:seeker_db}
    username: ${DB_LOGIN:seeker}
    password: ${DB_PASSWORD:seeker}
    hikari:
      poolName: Hikari
      auto-commit: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    drop-first: false # для dev - true, для prod - false.

  jpa:
    hibernate:
      ddl-auto: validate # для dev - update, для prod - validate.
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        check_nullability: true
        jdbc:
          # Hibernate прозрачно отключает пакетную вставку на уровне JDBC, если вы используете генератор IDENTITY
          batch_size: 10
          batch_versioned_data: true
        order_updates: true
        connection:
          # autocommit: true // не рекомендуется
          pool_size: 10
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  servlet:
    multipart:
      enabled: true
      location: ${MULTIPART_LOCATION:./temp/}
      max-file-size: ${MAX_MULTIPART_FILE_SIZE:50MB}
      max-request-size: ${MAX_MULTIPART_REQUEST_SIZE:50MB}

app:
  #  Настройка размера парсимых документов:
  poiZipSecureMinInflateRatio: ${POI_MIN_INFLATE_RATIO:0.01}
  poiZipSecureMaxFileCount: ${POI_MAX_FILE_COUNT:1500}
  #  Сколько ячеек минимум должно быть не пустыми в строке для сохранения её в БД:
  minFilledCellRowSave: ${MIN_FILLED_CELL_ROW_SAVE:2}
  admin-ip: ${ADMIN_IP:0:0:0:0:0:0:0:1}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    config-url: "${API_DOCS_MAIN_URI:${server.servlet.context-path:}}/v3/api-docs/swagger-config"
    url: "${API_DOCS_MAIN_URI:${server.servlet.context-path:}}/v3/api-docs"

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    elasticsearch:
      enabled: false
