logging:
  level:
    root: INFO
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/seeker}
  compression:
    enabled: true


spring:
  main:
    allow-circular-references: false
    lazy-initialization: false # для dev - false, для prod - true.
    allow-bean-definition-overriding: false

  application:
    name: ExcelSeekerService
    version: 0.1.1

  profiles:
    active: dev
    default: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:seeker_db}
    username: ${DB_LOGIN:seeker}
    password: ${DB_PASSWORD:seeker}
    hikari:
      poolName: Hikari
      auto-commit: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    drop-first: true # для dev - true, для prod - false.

  jpa:
    hibernate:
      ddl-auto: update # для dev - update, для prod - validate.
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        check_nullability: true
        jdbc:
          # Hibernate прозрачно отключает пакетную вставку на уровне JDBC, если вы используете генератор IDENTITY
          batch_size: 10
          batch_versioned_data: true
        order_updates: true
        connection:
          # autocommit: true // не рекомендуется
          pool_size: 10
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  data:
    elasticsearch:
      repositories:
        enabled: true

  servlet:
    multipart:
      enabled: true
      location: ${MULTIPART_LOCATION:./temp/}
      max-file-size: ${MAX_MULTIPART_FILE_SIZE:50MB}
      max-request-size: ${MAX_MULTIPART_REQUEST_SIZE:50MB}

app:
  notifyUrl: ${NOTIFY_SERVICE_URL:https://none.none.dev/seeker/notification/send}
  poiZipSecureMinInflateRatio: ${POI_MIN_INFLATE_RATIO:0.01}
  poiZipSecureMaxFileCount: ${POI_MAX_FILE_COUNT:1500}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    config-url: "${API_DOCS_MAIN_URI:${server.servlet.context-path:}}/v3/api-docs/swagger-config"
    url: "${API_DOCS_MAIN_URI:${server.servlet.context-path:}}/v3/api-docs"

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    elasticsearch:
      enabled: false
